# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['studio_gui.py'],
    pathex=[],
    binaries=[
        ('scan_engine.dll', '.'),
        ('kernel_driver/driver_wrapper.py', 'kernel_driver'),
        ('kernel_driver/hybrid_memory.py', 'kernel_driver'),
        ('kernel_driver/scanner_integration.py', 'kernel_driver'),
    ],
    datas=[('templates', 'templates')],
    hiddenimports=[
        'memory_scanner',
        'scan_engine',
        'themes',
        'trainer_compiler',
        'debugger',
        'stealth_debugger',
        'debugger_unified',
        'breakpoint_manager',
        'hotkey_manager',
        'disassembly_view',
        'memory_watch',
        'call_stack_tracer',
        'scripting_api',
        'hex_memory_viewer',
        'capstone',
        'yaml',
        'yaml.cyaml',
        'yaml.error',
        'yaml.nodes',
        'yaml.tokens',
        'struct',
        'pefile',
        'kernel_driver.driver_wrapper',
        'kernel_driver.hybrid_memory',
        'kernel_driver.scanner_integration',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MoStudio - beta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
)
