// trainer_template.cpp — compiled into a standalone .exe trainer
// GENERATED BY MomoTrainer Studio. Do not edit by hand; edit the .yaml instead.
//
// Build:  g++ -O2 -mwindows -o trainer.exe trainer_template.cpp -luser32 -lgdi32
//
// Runtime requirements:
//   - Windows 10/11
//   - The target game is a single-player game the user owns
//   - Process must be running with the same architecture as this exe

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>
#include <tlhelp32.h>

// ============================================================
// Brand
// ============================================================
static const char* BRAND_FULL  = "MomoTrainer — by Momo aka Steav Beoung Salang";

// ============================================================
// Virtual key constants (so the YAML can use VK_F8 etc.)
// ============================================================
static int vk_from_name(const char* s) {
    if (!s) return 0;
    if (!strcmp(s, "VK_F1"))  return VK_F1;
    if (!strcmp(s, "VK_F2"))  return VK_F2;
    if (!strcmp(s, "VK_F4"))  return VK_F4;
    if (!strcmp(s, "VK_F5"))  return VK_F5;
    if (!strcmp(s, "VK_F6"))  return VK_F6;
    if (!strcmp(s, "VK_F7"))  return VK_F7;
    if (!strcmp(s, "VK_F8"))  return VK_F8;
    if (!strcmp(s, "VK_F9"))  return VK_F9;
    if (!strcmp(s, "VK_F10")) return VK_F10;
    if (!strcmp(s, "VK_F11")) return VK_F11;
    if (!strcmp(s, "VK_F12")) return VK_F12;
    if (!strcmp(s, "VK_INSERT")) return VK_INSERT;
    if (!strcmp(s, "VK_HOME"))    return VK_HOME;
    if (!strcmp(s, "VK_END"))     return VK_END;
    if (!strcmp(s, "VK_DELETE"))  return VK_DELETE;
    if (!strcmp(s, "VK_NUMPAD0")) return VK_NUMPAD0;
    return 0;
}

// ============================================================
// Process helpers
// ============================================================
static DWORD find_pid_by_name(const char* exe_name) {
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snap == INVALID_HANDLE_VALUE) return 0;
    PROCESSENTRY32 pe = {};
    pe.dwSize = sizeof(pe);
    DWORD pid = 0;
    if (Process32First(snap, &pe)) {
        do {
            if (_stricmp(pe.szExeFile, exe_name) == 0) {
                pid = pe.th32ProcessID;
                break;
            }
        } while (Process32Next(snap, &pe));
    }
    CloseHandle(snap);
    return pid;
}

static uintptr_t get_module_base(DWORD pid, const char* module_name) {
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, pid);
    if (snap == INVALID_HANDLE_VALUE) return 0;
    MODULEENTRY32 me = {};
    me.dwSize = sizeof(me);
    uintptr_t base = 0;
    if (Module32First(snap, &me)) {
        do {
            if (_stricmp(me.szModule, module_name) == 0) {
                base = (uintptr_t)me.modBaseAddr;
                break;
            }
        } while (Module32Next(snap, &me));
    }
    CloseHandle(snap);
    return base;
}

// ============================================================
// Read/Write helpers (bounded to single-player scope)
// ============================================================
static bool read_bytes(HANDLE h, uintptr_t addr, void* out, size_t n) {
    SIZE_T got = 0;
    return ReadProcessMemory(h, (LPCVOID)addr, out, n, &got) && got == n;
}

static bool write_bytes(HANDLE h, uintptr_t addr, const void* in, size_t n) {
    SIZE_T put = 0;
    return WriteProcessMemory(h, (LPVOID)addr, in, n, &put) && put == n;
}

// Walk a pointer chain. base+offsets[0]+offsets[1]+...
// Each step dereferences a uintptr_t unless `width` is given.
static uintptr_t walk_pointer_chain(HANDLE h, uintptr_t base,
                                    const std::vector<uintptr_t>& offsets) {
    uintptr_t cur = base;
    for (size_t i = 0; i < offsets.size(); ++i) {
        cur += offsets[i];
        if (i + 1 < offsets.size()) {
            uintptr_t next = 0;
            if (!read_bytes(h, cur, &next, sizeof(next))) return 0;
            cur = next;
            if (cur == 0) return 0;  // null guard
        }
    }
    return cur;
}

// Parse "GameName.exe+0x00123456" -> base address (looked up at runtime)
static uintptr_t resolve_address(HANDLE h, DWORD pid, const char* expr) {
    if (!expr || !*expr) return 0;
    const char* plus = strchr(expr, '+');
    if (!plus) {
        // raw hex
        return strtoull(expr, nullptr, 16);
    }
    std::string module(expr, plus - expr);
    uintptr_t offset = strtoull(plus + 1, nullptr, 16);
    uintptr_t base = get_module_base(pid, module.c_str());
    if (!base) return 0;
    return base + offset;
}

// ============================================================
// Feature descriptor (generated from YAML)
// ============================================================
enum class FType { VALUE, FREEZE, NUDGE };

struct Feature {
    const char* name;
    FType type;
    bool is_pointer;            // false = absolute address
    uintptr_t addr;             // if is_pointer=false
    uintptr_t ptr_base;         // if is_pointer=true (already-resolved)
    std::vector<uintptr_t> ptr_offsets;
    uintptr_t ptr_resolved;     // last resolved chain addr (cached)
    int64_t   value;            // for VALUE / FREEZE
    double    value_f;          // for FLOAT
    int64_t   delta;            // for NUDGE
    int       width;            // 1, 2, 4, 8
    bool      is_float;
    bool      enabled;
    int       interval_ms;      // for FREEZE
};

// ============================================================
// GENERATED FEATURE TABLE
// This block is rewritten by MomoTrainer Studio when you save
// a trainer. Don't edit by hand or your changes get overwritten.
// ============================================================
static Feature g_features[] = {
    // {{FEATURES_BEGIN}}
    // {{FEATURES_END}}
};
static int g_feature_count() { return sizeof(g_features)/sizeof(g_features[0]); }

// ============================================================
// GENERATED ACTION TABLE (one-shot hotkey triggers)
// ============================================================
struct Action {
    const char* name;
    int         vk;
    uintptr_t   addr;
    int64_t     value;
    int         width;
    bool        is_float;
};
static Action g_actions[] = {
    // {{ACTIONS_BEGIN}}
    // {{ACTIONS_END}}
};
static int g_action_count() { return sizeof(g_actions)/sizeof(g_actions[0]); }

// ============================================================
// GENERATED CONFIG
// ============================================================
static const char*  CFG_GAME             = "{{GAME}}";
static int          CFG_HOTKEY_TOGGLE    = {{HOTKEY_TOGGLE}};
static int          CFG_HOTKEY_PANIC     = {{HOTKEY_PANIC}};
static int          CFG_WINDOW_W         = {{WIN_W}};
static int          CFG_WINDOW_H         = {{WIN_H}};
static unsigned     CFG_WINDOW_COLOR     = {{WIN_COLOR}};

// ============================================================
// UI: a simple Win32 window with checkboxes
// ============================================================
static HWND     g_hwnd = nullptr;
static HANDLE   g_proc = nullptr;
static DWORD    g_pid  = 0;
static bool     g_visible = true;
static std::vector<HWND> g_checkboxes;
static HFONT    g_font = nullptr;

static LRESULT CALLBACK wnd_proc(HWND h, UINT m, WPARAM w, LPARAM l) {
    switch (m) {
    case WM_COMMAND:
        if (HIWORD(w) == BN_CLICKED) {
            int id = LOWORD(w) - 1000;
            if (id >= 0 && id < g_feature_count()) {
                g_features[id].enabled = !g_features[id].enabled;
                // capture original if turning on, restore if turning off
                if (g_features[id].enabled && !g_features[id].is_pointer) {
                    uintptr_t a = g_features[id].addr;
                    int64_t orig = 0;
                    read_bytes(g_proc, a, &orig, g_features[id].width);
                    // store in delta (negative offset for restore)
                    g_features[id].delta = -orig;
                }
            }
        }
        return 0;
    case WM_PAINT: {
        PAINTSTRUCT ps;
        HDC dc = BeginPaint(h, &ps);
        RECT r; GetClientRect(h, &r);
        HBRUSH bg = CreateSolidBrush(CFG_WINDOW_COLOR);
        FillRect(dc, &r, bg);
        DeleteObject(bg);
        SetBkMode(dc, TRANSPARENT);
        SetTextColor(dc, RGB(0, 0, 0));
        SelectObject(dc, g_font);
        EndPaint(h, &ps);
        return 0;
    }
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProc(h, m, w, l);
}

static void build_window(HINSTANCE inst) {
    WNDCLASS wc = {};
    wc.lpfnWndProc   = wnd_proc;
    wc.hInstance      = inst;
    wc.lpszClassName  = "MomoTrainer";
    wc.hbrBackground  = nullptr;  // we paint in WM_PAINT
    RegisterClass(&wc);

    g_hwnd = CreateWindowEx(WS_EX_TOPMOST | WS_EX_TOOLWINDOW,
        "MomoTrainer", BRAND_FULL,
        WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU,
        100, 100, CFG_WINDOW_W, CFG_WINDOW_H,
        nullptr, nullptr, inst, nullptr);

    g_font = CreateFont(16, 0, 0, 0, FW_NORMAL, FALSE, FALSE, FALSE,
        DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
        DEFAULT_QUALITY, DEFAULT_PITCH, "Consolas");

    int y = 10;
    for (int i = 0; i < g_feature_count(); ++i) {
        HWND cb = CreateWindow("BUTTON", g_features[i].name,
            WS_VISIBLE | WS_CHILD | BS_AUTOCHECKBOX,
            10, y, CFG_WINDOW_W - 20, 24,
            g_hwnd, reinterpret_cast<HMENU>(static_cast<UINT_PTR>(1000 + i)), inst, nullptr);
        SendMessage(cb, WM_SETFONT, (WPARAM)g_font, TRUE);
        g_checkboxes.push_back(cb);
        y += 28;
    }
}

// ============================================================
// Worker thread: refresh pointer chains + apply features
// ============================================================
static DWORD WINAPI worker_thread(LPVOID) {
    while (g_visible || true) {  // keep running even when window hidden
        Sleep(16);
        if (g_pid == 0) {
            g_pid = find_pid_by_name(CFG_GAME);
            if (g_pid == 0) continue;
            g_proc = OpenProcess(PROCESS_VM_READ | PROCESS_VM_WRITE |
                                  PROCESS_VM_OPERATION | PROCESS_QUERY_INFORMATION,
                                 FALSE, g_pid);
            if (!g_proc) { g_pid = 0; continue; }
        } else {
            // check process still alive
            DWORD exit_code;
            if (!GetExitCodeProcess(g_proc, &exit_code) || exit_code != STILL_ACTIVE) {
                CloseHandle(g_proc); g_proc = nullptr; g_pid = 0;
                continue;
            }
        }
        for (int i = 0; i < g_feature_count(); ++i) {
            Feature& f = g_features[i];
            if (!f.enabled) continue;
            uintptr_t a = 0;
            if (f.is_pointer) {
                a = walk_pointer_chain(g_proc, f.ptr_base, f.ptr_offsets);
                if (!a) continue;
                f.ptr_resolved = a;
            } else {
                a = f.addr;
            }
            if (f.type == FType::VALUE || f.type == FType::FREEZE) {
                if (f.is_float) write_bytes(g_proc, a, &f.value_f, f.width);
                else            write_bytes(g_proc, a, &f.value,   f.width);
            } else if (f.type == FType::NUDGE) {
                int64_t cur = 0;
                read_bytes(g_proc, a, &cur, f.width);
                cur += f.delta;
                write_bytes(g_proc, a, &cur, f.width);
            }
        }
    }
    return 0;
}

// ============================================================
// Hotkey thread: action triggers
// ============================================================
static DWORD WINAPI hotkey_thread(LPVOID) {
    while (true) {
        Sleep(30);
        for (int i = 0; i < g_action_count(); ++i) {
            if ((GetAsyncKeyState(g_actions[i].vk) & 1) &&
                g_proc != nullptr) {
                if (g_actions[i].is_float)
                    write_bytes(g_proc, g_actions[i].addr, &g_actions[i].value, g_actions[i].width);
                else
                    write_bytes(g_proc, g_actions[i].addr, &g_actions[i].value, g_actions[i].width);
                Sleep(300);  // simple debounce
            }
        }
    }
}

// ============================================================
// Entry
// ============================================================
static void resolve_pointer_bases();  // injected by trainer_compiler.py

int WINAPI WinMain(HINSTANCE inst, HINSTANCE, LPSTR, int) {
    build_window(inst);
    ShowWindow(g_hwnd, SW_SHOW);

    CreateThread(nullptr, 0, worker_thread, nullptr, 0, NULL);
    CreateThread(nullptr, 0, hotkey_thread,  nullptr, 0, NULL);

    MSG msg;
    while (GetMessage(&msg, nullptr, 0, 0)) {
        // toggle visibility
        if (msg.message == WM_HOTKEY || (msg.message == WM_KEYDOWN && msg.wParam == CFG_HOTKEY_TOGGLE)) {
            g_visible = !g_visible;
            ShowWindow(g_hwnd, g_visible ? SW_SHOW : SW_HIDE);
            continue;
        }
        if (msg.message == WM_KEYDOWN && msg.wParam == CFG_HOTKEY_PANIC) {
            for (int i = 0; i < g_feature_count(); ++i) g_features[i].enabled = false;
            for (auto cb : g_checkboxes) SendMessage(cb, BM_SETCHECK, BST_UNCHECKED, 0);
            continue;
        }
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    return 0;
}